GET http://localhost:5000/offers?limit=20 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImJhYnVzaGthMzNAbWFpbC5jb20iLCJuYW1lIjoiYmFidXNoa2EiLCJpZCI6IjY3Mjc3ZTE5NmUwMmU0MTE1ZmNhMzJlOCIsImlhdCI6MTczMDY0MTQ2NCwiZXhwIjoxNzMwODE0MjY0fQ.96uEZEvY1pQiNuH-eJ1d9_2L8GyWNAZMCCaPHK2xF28

###

GET http://localhost:5000/offers/67278c476c7f83791776f130 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InpkdkBodG1sYWNhZGVteS5ydSIsIm5hbWUiOiJEZW5pcyIsImlkIjoiNjcyNWRkOGU0ZGVjYTc0MTMxNDE1ZWJhIiwiaWF0IjoxNzMwNTM1NzUzLCJleHAiOjE3MzA3MDg1NTN9.lgO9OtWz5m8QCUf__wHXWE1N5CDAnFIBRIjuk5CGBKk

{
  "title": "Test title",
  "description": "Test description of offer",
  "cityName": "Paris",
  "images":[
    "https://16.design.htmlacademy.pro/static/hotel/1.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/2.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/3.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/4.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/5.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/6.jpg"
  ],
  "isPremium": true,
  "rating": 5,
  "type": "house",
  "bedroomsCount": 3,
  "guestsCount": 6,
  "price": 100,
  "goods": ["Breakfast"],
  "location": {
    "latitude": 48.85661,
    "longitude": 2.351499
  }
}

###

PUT http://localhost:5000/offers/67260cd52ebc34915a0f2aa6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InpkdkBodG1sYWNhZGVteS5ydSIsIm5hbWUiOiJEZW5pcyIsImlkIjoiNjcyNWRkOGU0ZGVjYTc0MTMxNDE1ZWJhIiwiaWF0IjoxNzMwNTM1NzUzLCJleHAiOjE3MzA3MDg1NTN9.lgO9OtWz5m8QCUf__wHXWE1N5CDAnFIBRIjuk5CGBKk

{
  "title": "Test title",
  "description": "Test description of offer",
  "postDate": "2024-11-01T01:55:40.283Z",
  "city": "Pariss",
  "images":[
    "https://16.design.htmlacademy.pro/static/hotel/1.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/2.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/3.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/4.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/5.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/6.jpg"
  ],
  "isPremium": true,
  "rating": 5,
  "type": "house",
  "bedroomsCount": 3,
  "guestsCount": 6,
  "price": 1000,
  "goods": ["Breakfast"]
}

###
DELETE http://localhost:5000/offers/67260e85719435d3c9cc6eb4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InpkdkBodG1sYWNhZGVteS5ydSIsIm5hbWUiOiJEZW5pcyIsImlkIjoiNjcyNWRkOGU0ZGVjYTc0MTMxNDE1ZWJhIiwiaWF0IjoxNzMwNTM1NzUzLCJleHAiOjE3MzA3MDg1NTN9.lgO9OtWz5m8QCUf__wHXWE1N5CDAnFIBRIjuk5CGBKk

###
DELETE http://localhost:5000/offers/67260e85719435d3c9cc6eb4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InpkdjJAaHRtbGFjYWRlbXkucnUiLCJuYW1lIjoiRGVuaXMiLCJpZCI6IjY3MjVlMTg3YThhNzNiYWQ1ODlhMjYzMyIsImlhdCI6MTczMDU2MjUwMywiZXhwIjoxNzMwNzM1MzAzfQ.YMfMQPpqQjWboCcEUPXYocnF5Z9rr7A1ulSD4dG68BU

###

GET http://localhost:5000/offers/67271285088cc8e8730dee15/comments HTTP/1.1
Content-Type: application/json
