# Get mock data from fake server
GET http://localhost:3123/api HTTP/1.1

###

POST http://localhost:5000/users/register HTTP/1.1
Content-type: application/json

{
  "name": "Keks1234",
  "email": "keks2134@htmlacademy.ru",
  "avatarUrl": "qwerty",
  "isPro": "true",
  "password": "123456"
}

###

GET http://localhost:5000/offers HTTP/1.1
Content-Type: application/json
