# Get mock data from fake server
GET http://localhost:3123/api HTTP/1.1

###

POST http://localhost:5000/users/register HTTP/1.1
Content-type: application/json

{
  "name": "Keks1234",
  "email": "keks2134@htmlacademy.ru",
  "avatarUrl": "qwerty",
  "isPro": true,
  "password": "123456"
}

###

POST http://localhost:5000/users/login HTTP/1.1
Content-type: application/json

{
  "email": "keks2134@htmlacademy.ru",
  "password": "123456"
}

###

GET http://localhost:5000/offers?limit=20 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:5000/offers/Cologne/premium HTTP/1.1
Content-Type: application/json

###

GET http://localhost:5000/offers/671392632f0a76b7d35d111e HTTP/1.1
Content-Type: application/json

###

PATCH http://localhost:5000/offers/67138f19716a710e06407bbe/change-favorite HTTP/1.1
Content-Type: application/json

###

DELETE http://localhost:5000/offers/67161e46b16a807dfa80ceb5 HTTP/1.1
Content-Type: application/json


###

POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "The house among olive",
  "description": "Design interior in most sympathetic area!",
  "postDate": "2024-09-07T01:55:40.283Z",
  "city": "Paris",
  "previewImage": "https://16.design.htmlacademy.pro/static/hotel/1.jpg",
  "images": [
    "https://16.design.htmlacademy.pro/static/hotel/1.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/2.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/3.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/4.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/5.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/6.jpg"
  ],
  "isPremium": true,
  "isFavorite": true,
  "rating": 4.5,
  "type": "apartment",
  "bedroomsCount": 3,
  "guestsCount": 4,
  "price": 5000,
  "goods": [
    "Breakfast",
    "Air conditioning",
    "Laptop friendly workspace"
  ],
  "userId": "6329c3d6a04ab1061c6425ea",
  "location": {
    "latitude": 48.85661,
    "longitude": 2.351499
  }
}

###
POST http://localhost:5000/comments/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3MyMTM0QGh0bWxhY2FkZW15LnJ1IiwibmFtZSI6Iktla3MxMjM0IiwiaWQiOiI2NzE2MWUzNmRmZTNlNGU4MDliOTM2MDMiLCJpYXQiOjE3MzAyMjIyNzcsImV4cCI6MTczMDM5NTA3N30.L5LeK8wV08o8jyex6o8VI4lQr0TfdldIEjdnTcMY8rg

{
  "offerId": "67138f19716a710e06407bbe",
  "text": "Awesome!",
  "rating": 5
}

###
GET http://localhost:5000/offers/67138f19716a710e06407bbe/comments HTTP/1.1
Content-Type: application/json

###

POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

{
  "title": "The house among olive",
  "description": "Design interior in most sympathetic area!",
  "postDate": "2024-09-07T01:55:40.283Z",
  "city": "Paris",
  "previewImage": "https://16.design.htmlacademy.pro/static/hotel/1.jpg",
  "images": [
    "https://16.design.htmlacademy.pro/static/hotel/1.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/2.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/3.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/4.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/5.jpg",
    "https://16.design.htmlacademy.pro/static/hotel/6.jpg"
  ],
  "isPremium": true,
  "isFavorite": true,
  "rating": 4.5,
  "type": "apartment",
  "bedroomsCount": 3,
  "guestsCount": 4,
  "price": 5000,
  "goods": [
    "Breakfast",
    "Air conditioning",
    "Laptop friendly workspace"
  ],
  "userId": "6329c3d6a04ab1061c6425ea",
  "location": {
    "latitude": 48.85661,
    "longitude": 2.351499
  }
}

###

## Отправить изображение

POST http://localhost:5000/users/67138f19716a710e06407bbc/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< C:\Users\Den\Pictures\2.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##

###
GET http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3MyMTM0QGh0bWxhY2FkZW15LnJ1IiwibmFtZSI6Iktla3MxMjM0IiwiaWQiOiI2NzE2MWUzNmRmZTNlNGU4MDliOTM2MDMiLCJpYXQiOjE3MzAyMjIyNzcsImV4cCI6MTczMDM5NTA3N30.L5LeK8wV08o8jyex6o8VI4lQr0TfdldIEjdnTcMY8rg
